[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
coston2 = "${RPC_URL}"
flare = "${RPC_URL}"

